# Generated by Django 4.2.7 on 2025-12-23 07:46
# Updated: Made conditional for empty database

from django.db import migrations


def alter_model_options_if_exists(apps, schema_editor):
    """Изменяем опции модели только если она существует"""
    try:
        # Проверяем, существует ли таблица
        cursor = schema_editor.connection.cursor()
        cursor.execute("SELECT 1 FROM information_schema.tables WHERE table_name='projects_projectchatmessage' LIMIT 1")
        if cursor.fetchone():
            # Таблица существует, применяем изменения
            from django.db import connection
            with connection.cursor() as cursor:
                # Опции модели уже применены через CreateModel в 0002, поэтому здесь ничего не делаем
                pass
    except Exception:
        # Игнорируем ошибки, если таблица не существует (база данных пустая)
        pass


def reverse_alter_model_options(apps, schema_editor):
    """Обратная операция (noop)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(
            alter_model_options_if_exists,
            reverse_alter_model_options,
        ),
    ]
