# Generated by Django 4.2.7 on 2025-12-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectchatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение в чате', 'verbose_name_plural': 'Сообщения в чате'},
        ),
    ]
