# Generated by Django 4.2.7 on 2026-01-29 12:46
# Fixed: These models were already removed in migration 0004

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_old_models_create_new'),
    ]

    operations = [
        # All old models (ProjectChatMessage, ProjectMember, DevelopmentStage, StageHint)
        # were already removed in migration 0004, so this migration is a noop
    ]
