# Generated by Django 4.2.7 on 2026-01-29 13:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_remove_projectchatmessage_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Отмечено')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Отметка преподавателя',
                'verbose_name_plural': 'Отметки преподавателей',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/', verbose_name='Файл')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Файл проекта',
                'verbose_name_plural': 'Файлы проектов',
                'ordering': ['-created_at'],
            },
        ),
        # Старые модели (ProjectChatMessage, ProjectMember, StageHint) уже удалены в миграции 0004
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['section', 'order', 'created_at'], 'verbose_name': 'База знаний', 'verbose_name_plural': 'База знаний'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий к проекту', 'verbose_name_plural': 'Комментарии к проектам'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Этап', 'verbose_name_plural': 'Этапы'},
        ),
        migrations.AlterModelOptions(
            name='stagecomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий к этапу', 'verbose_name_plural': 'Комментарии к этапам'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-created_at'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['-created_at'], 'verbose_name': 'Участник команды', 'verbose_name_plural': 'Участники команд'},
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='kanban_column',
            field=models.CharField(choices=[('column1', 'Колонка 1'), ('column2', 'Колонка 2'), ('column3', 'Колонка 3')], default='column1', max_length=20, verbose_name='Колонка канбан-доски'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок в колонке'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='section',
            field=models.CharField(choices=[('team', 'Команда'), ('project_passport', 'Паспорт проекта'), ('stage', 'Этап'), ('task', 'Задача')], max_length=50, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='passport',
            field=models.TextField(blank=True, verbose_name='Паспорт проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлен на проверку'), ('approved', 'Принято'), ('revision', 'На доработке'), ('rejected', 'Отклонено')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки на проверку'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='artifact',
            field=models.FileField(blank=True, null=True, upload_to='artifacts/', verbose_name='Артефакт'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='artifact_description',
            field=models.TextField(blank=True, verbose_name='Описание артефакта'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='criteria',
            field=models.TextField(blank=True, verbose_name='Критерии приемки'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название этапа'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stages', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В работе'), ('submitted', 'На проверке'), ('approved', 'Принято'), ('revision', 'На доработке')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки на проверку'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='stagecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='stagecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='stagecomment',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.stage', verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='stagecomment',
            name='text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='stagecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Назначил'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Назначена'),
        ),
        migrations.AlterField(
            model_name='task',
            name='blocker',
            field=models.TextField(blank=True, verbose_name='Блокер'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.stage', verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('returned', 'Возвращена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL, verbose_name='Приглашен'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждено участие'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата присоединения'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('team_leader', 'Тимлид'), ('member', 'Участник')], default='member', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='projects.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        # Старые модели (DevelopmentStage, ProjectChatMessage, ProjectMember, StageHint) уже удалены в миграции 0004
        migrations.AddField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_project_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AddField(
            model_name='projectcheck',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_checks', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='projectcheck',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_checks', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AlterUniqueTogether(
            name='projectcheck',
            unique_together={('project', 'teacher')},
        ),
    ]
