# Generated by Django 4.2.7 on 2026-01-29 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_projectcheck_projectfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название карточки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('column', models.CharField(choices=[('column1', 'Колонка 1'), ('column2', 'Колонка 2'), ('column3', 'Колонка 3')], default='column1', max_length=20, verbose_name='Колонка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок в колонке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_kanban_cards', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_cards', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Карточка канбан-доски',
                'verbose_name_plural': 'Карточки канбан-доски',
                'ordering': ['column', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='KanbanCardCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Отмечено')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_checks', to='projects.kanbancard', verbose_name='Карточка')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_card_checks', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Отметка преподавателя на карточке',
                'verbose_name_plural': 'Отметки преподавателей на карточках',
                'ordering': ['-updated_at'],
                'unique_together': {('card', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='KanbanCardComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_card_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.kanbancard', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Комментарий к карточке',
                'verbose_name_plural': 'Комментарии к карточкам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KanbanCardFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='kanban_files/', verbose_name='Файл')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.kanbancard', verbose_name='Карточка')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_kanban_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл карточки',
                'verbose_name_plural': 'Файлы карточек',
                'ordering': ['-created_at'],
            },
        ),
        # Старые модели (ProjectChatMessage, ProjectMember, DevelopmentStage, StageHint) уже удалены в миграции 0004
    ]
