# Generated by Django 4.2.7 on 2026-01-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_kanbancard_kanbancardcheck_kanbancardcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='passport_text',
            field=models.TextField(blank=True, verbose_name='Текст паспорта проекта (опционально)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='project_passports/', verbose_name='Паспорт проекта (файл)'),
        ),
    ]
